name: ❓ Question
description: Ask a question about diffx usage or functionality
title: "[Question]: "
labels: ["type: question", "status: needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your question! While we encourage using [GitHub Discussions](https://github.com/kako-jun/diffx/discussions) for general questions, this template is here if you prefer issues.

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know about diffx?
      placeholder: How do I compare JSON files while ignoring certain keys?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: |
        Provide any relevant context about what you're trying to achieve.
        Include any code, commands, or configuration you've tried.
      placeholder: |
        I'm trying to compare configuration files that have timestamps that change frequently.
        I've tried using --ignore-keys-regex but I'm not sure about the syntax...

  - type: textarea
    id: attempted_solutions
    attributes:
      label: What I've Tried
      description: |
        What have you already tried? Include any documentation you've checked.
      placeholder: |
        I've checked:
        - The README.md file
        - The documentation in docs/user-guide/
        - Searched existing issues
        
        I've tried:
        - diffx file1.json file2.json --ignore-keys-regex "timestamp"
        - Looking at the --help output

  - type: dropdown
    id: urgency
    attributes:
      label: Urgency
      description: How urgent is this question for you?
      options:
        - Low - Just curious
        - Medium - Would help my current work
        - High - Blocking my project
    validations:
      required: true

  - type: textarea
    id: version_info
    attributes:
      label: Environment (Optional)
      description: |
        If relevant to your question, provide version information
      placeholder: |
        diffx version: 0.2.0
        OS: Ubuntu 22.04
        Use case: CI/CD configuration validation

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm you've done the following
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: I have checked the documentation
          required: true
        - label: This is a specific question, not a bug report or feature request
          required: true