[package]
name = "diffx-core"
version = "0.2.0"
edition = "2021"
authors = ["kako-jun"]
description = "Core library for structured data diffing (JSON, YAML, TOML, XML, INI, CSV)"
license = "MIT"
repository = "https://github.com/kako-jun/diffx"
homepage = "https://github.com/kako-jun/diffx"
documentation = "https://docs.rs/diffx-core"
keywords = ["diff", "json", "yaml", "toml", "structured-data"]
categories = ["command-line-utilities", "data-structures", "parsing"]

[dependencies]
anyhow = "1.0.98"
csv = "1.3.0"
configparser = "3.0.0"
quick-xml = { version = "0.31.0", features = ["serialize"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_yml = "0.0.12"
toml = "0.8.23"
regex = "1.10.5"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "diff_benchmark"
harness = false
