[package]
name = "diffx-core"
version = "0.1.0"
edition = "2021"
authors = ["kako-jun"]

[dependencies]
anyhow = "1.0.98"
csv = "1.3.0"
configparser = "3.0.0"
quick-xml = { version = "0.31.0", features = ["serialize"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_yaml = "0.9.34"
toml = "0.8.23"
regex = "1.10.5"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "diff_benchmark"
harness = false
