name: Performance Benchmark

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmark:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-bench-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Run benchmarks
      run: |
        cargo bench --package diffx-core > benchmark_results.txt
        cat benchmark_results.txt
        
    - name: Check performance regression
      run: |
        # Show benchmark results for debugging
        echo "=== Benchmark Results ==="
        cat benchmark_results.txt
        echo "=========================="
        
        # Simple approach: just extract the middle value from criterion output
        # Format: "time:   [969.75 ns 970.33 ns 971.10 ns]" - we want the middle value
        SMALL_LINE=$(grep "diff_small_json" benchmark_results.txt -A 1 | grep "time:" | head -1)
        LARGE_LINE=$(grep "diff_large_json" benchmark_results.txt -A 1 | grep "time:" | head -1)
        
        echo "Small line: $SMALL_LINE"
        echo "Large line: $LARGE_LINE"
        
        # Extract middle value and convert all to nanoseconds for consistent comparison
        SMALL_MIDDLE=$(echo "$SMALL_LINE" | awk '{print $4}' | tr -d '[]')
        LARGE_MIDDLE=$(echo "$LARGE_LINE" | awk '{print $4}' | tr -d '[]')
        
        echo "Small middle: $SMALL_MIDDLE"
        echo "Large middle: $LARGE_MIDDLE"
        
        # Convert to microseconds (assuming input is nanoseconds from criterion)
        SMALL_TIME_US=$(echo "scale=3; $SMALL_MIDDLE / 1000" | bc -l)
        LARGE_TIME_US=$(echo "scale=3; $LARGE_MIDDLE / 1000" | bc -l)
        
        echo "Small JSON diff time: ${SMALL_TIME_US}µs"
        echo "Large JSON diff time: ${LARGE_TIME_US}µs"
        
        # Performance thresholds (more realistic for modern systems)
        SMALL_THRESHOLD=5.0   # µs (allowing for CI noise)
        LARGE_THRESHOLD=1000  # µs (allowing for CI noise)
        
        # Check if performance is within acceptable range
        if (( $(echo "$SMALL_TIME_US > $SMALL_THRESHOLD" | bc -l) )); then
          echo "❌ Performance regression detected in small JSON test!"
          echo "Expected: < ${SMALL_THRESHOLD}µs, Got: ${SMALL_TIME_US}µs"
          exit 1
        fi
        
        if (( $(echo "$LARGE_TIME_US > $LARGE_THRESHOLD" | bc -l) )); then
          echo "❌ Performance regression detected in large JSON test!"
          echo "Expected: < ${LARGE_THRESHOLD}µs, Got: ${LARGE_TIME_US}µs"
          exit 1
        fi
        
        echo "✅ Performance tests passed!"
        echo "Small JSON: ${SMALL_TIME_US}µs (threshold: ${SMALL_THRESHOLD}µs)"
        echo "Large JSON: ${LARGE_TIME_US}µs (threshold: ${LARGE_THRESHOLD}µs)"
        
    - name: Upload benchmark results
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results
        path: |
          benchmark_results.txt
          target/criterion/
        retention-days: 30

  benchmark-comparison:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout PR
      uses: actions/checkout@v4
      
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-bench-pr-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Run PR benchmarks
      run: |
        cargo bench --package diffx-core > pr_benchmark.txt
        echo "## 📊 Performance Impact" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Benchmark Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        cat pr_benchmark.txt >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Performance Thresholds" >> $GITHUB_STEP_SUMMARY
        echo "- Small JSON diff: < 5.0µs" >> $GITHUB_STEP_SUMMARY
        echo "- Large JSON diff: < 1000µs" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        # Extract and report current performance using same logic as main job
        SMALL_LINE=$(grep "diff_small_json" pr_benchmark.txt -A 1 | grep "time:" | head -1)
        LARGE_LINE=$(grep "diff_large_json" pr_benchmark.txt -A 1 | grep "time:" | head -1)
        
        SMALL_MIDDLE=$(echo "$SMALL_LINE" | awk '{print $4}' | tr -d '[]')
        LARGE_MIDDLE=$(echo "$LARGE_LINE" | awk '{print $4}' | tr -d '[]')
        
        SMALL_TIME_US=$(echo "scale=3; $SMALL_MIDDLE / 1000" | bc -l)
        LARGE_TIME_US=$(echo "scale=3; $LARGE_MIDDLE / 1000" | bc -l)
        
        echo "### Current Performance" >> $GITHUB_STEP_SUMMARY
        echo "- Small JSON: ${SMALL_TIME_US}µs" >> $GITHUB_STEP_SUMMARY
        echo "- Large JSON: ${LARGE_TIME_US}µs" >> $GITHUB_STEP_SUMMARY