name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Check formatting
      run: cargo fmt --all --check
      
    - name: Run Clippy
      run: cargo clippy --workspace --all-targets --all-features -- -D warnings
      
    - name: Build
      run: cargo build --workspace --verbose
      
    - name: Run tests
      run: cargo test --workspace --verbose
      
    - name: Quick performance check
      run: |
        # Light performance sanity check (just compilation and basic run)
        cargo build --release --package diffx-core
        echo "✅ Release build successful - performance optimizations applied"
