name: Publish All Packages

on:
  workflow_dispatch:
    inputs:
      publish_crates:
        description: 'Publish to crates.io'
        required: true
        type: boolean
        default: true
      publish_npm:
        description: 'Publish to npm'
        required: true
        type: boolean
        default: true
      publish_pypi:
        description: 'Publish to PyPI'
        required: true
        type: boolean
        default: true

env:
  CARGO_TERM_COLOR: always

jobs:
  publish-crates:
    if: github.event.inputs.publish_crates == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Publish to crates.io
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: |
        echo "📦 Publishing diffx-core to crates.io..."
        cargo publish --package diffx-core
        
        echo "⏳ Waiting for diffx-core to be available..."
        sleep 60
        
        echo "📦 Publishing diffx CLI to crates.io..."
        cargo publish --package diffx
        
        echo "✅ Successfully published to crates.io!"

  publish-npm:
    if: github.event.inputs.publish_npm == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install dependencies
      run: |
        cd diffx-npm
        npm ci
    
    - name: Build package
      run: |
        cd diffx-npm
        npm run build || echo "No build script"
    
    - name: Publish to npm
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        cd diffx-npm
        echo "📦 Publishing diffx-js to npm..."
        npm publish --access public
        echo "✅ Successfully published to npm!"

  publish-pypi:
    if: github.event.inputs.publish_pypi == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build package
      run: |
        cd diffx-python
        python -m build
    
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        cd diffx-python
        echo "📦 Publishing diffx-python to PyPI..."
        python -m twine upload dist/*
        echo "✅ Successfully published to PyPI!"

  summary:
    needs: [publish-crates, publish-npm, publish-pypi]
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Publication Summary
      run: |
        echo "🎉 Package Publication Summary"
        echo "=============================="
        
        if [ "${{ needs.publish-crates.result }}" = "success" ]; then
          echo "✅ crates.io: Published successfully"
        else
          echo "❌ crates.io: ${{ needs.publish-crates.result }}"
        fi
        
        if [ "${{ needs.publish-npm.result }}" = "success" ]; then
          echo "✅ npm: Published successfully"
        else
          echo "❌ npm: ${{ needs.publish-npm.result }}"
        fi
        
        if [ "${{ needs.publish-pypi.result }}" = "success" ]; then
          echo "✅ PyPI: Published successfully"
        else
          echo "❌ PyPI: ${{ needs.publish-pypi.result }}"
        fi
        
        echo ""
        echo "📋 Installation Commands:"
        echo "cargo install diffx"
        echo "npm install diffx-js"
        echo "pip install diffx-python"